# Generated by Django 5.2.4 on 2025-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.JSONField()),
                ('prompt', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('music', models.TextField(blank=True, max_length=120)),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cocktails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(default='llama3', max_length=50)),
            ],
        ),
    ]
