# Generated by Django 5.2.4 on 2025-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='translated_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
